name: products
services:
  db:
    image: postgres:alpine
    ports:
      - 15432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: products
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
    networks:
      - default

  api:
    build:
      context: .
      target: api
    depends_on:
      db:
        condition: service_started
    secrets:
      - source: api-env
        target: /var/www/html/.env
    configs:
      - source: fpm-www
        target: /etc/php82/php-fpm.d/www.conf
      - source: fpm-global
        target: /etc/php82/php-fpm.d/_global.conf
    volumes:
      - api-run:/run/php:rw
      - api-storage:/var/www/html/storage:rw
      - api-public:/var/www/html/public:rw
    networks:
      - default

  web-server:
    build:
      context: .
      target: web-server
    depends_on:
      api:
        condition: service_started
    configs:
      - source: web-conf
        target: /etc/nginx/conf.d/default.conf
    volumes:
      - api-run:/run/php:rw
      - api-public:/var/www/html/public:rw
    ports:
      - "${WEB_SERVER_PORT-14243}:80"
    networks:
      - default
  
  seeder:
    build:
      context: .
      target: seeder
    depends_on:
      db:
        condition: service_started
    secrets:
      - source: api-env
        target: /var/www/html/.env
    configs:
      - source: fpm-www
        target: /etc/php82/php-fpm.d/www.conf
      - source: fpm-global
        target: /etc/php82/php-fpm.d/_global.conf
    volumes:
      - api-run:/run/php:rw
      - api-storage:/var/www/html/storage:rw
      - api-public:/var/www/html/public:rw
    networks:
      - default
    profiles: [seed]

volumes:
  api-run:
  api-storage:
  api-public:
  db-data:

configs:
  fpm-www:
    file: ./docker/php-fpm-www.conf
  fpm-global:
    file: ./docker/php-fpm-global.conf
  web-conf:
    file: ./docker/products-nginx.conf

secrets:
  api-env:
    file: ./docker/api.env
